### ISSUE TITLE
Errors with zkg install zeek/spicy-plugin

### ISSUE THREAD

**Issue by neslog** [zeek/spicy-plugin#106]
I'm currently trying to build Zeek with spicy and receiving errors below are some details.

Red Hat Enterprise Linux release 8.5 (Ootpa)
Spicy - spicyc v1.5.0-dev.12 (1b38a6dc)
zeek version 4.0.3

Used pip3 to installl zeek/spicy-plugin
[spicy-plugin-build.log](https://github.com/zeek/spicy-plugin/files/8453258/spicy-plugin-build.log)

**Comment by bbannier** [comment]
Like you mentioned on Slack, you installed the centos8_stream RPM on RHEL8 which would be fortunate to work, but I suspect does not due to e.g., ABI issues.

I suggest you build Spicy on on your target RHEL system (or an equivalent system), and check whether still shows this issue. I am closing this issue for now, but please feel free to reopen it should you still see the issue after building a RHEL8 Spicy.
