### ISSUE TITLE
Allow analyzer to start analyzing partial connections

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy-plugin#135]
Zeek might be started after a connection was established; this leads to partial connections. We should allow attaching Spicy analyzers to such a connection. Ideally we'd start the analyzer in recovery mode so it can find a synchronization point.

**Comment by rsmmr** [comment]
Gonna assign this to me because I believe we left this at me trying to see what the current behavior is for one of our existing analyzers, and see if it might already work.

**Comment by rsmmr** [comment]
So turns out we already removed the check for partial connections and are indeed just feeding the data into the analyzer even if we start in the middle of the connection. That means that the analyzer will simply try to parse the data at that point. It might fail to do so, and will then either abort or trigger resynchronization if that's defined. 

This is probably often good enough. However, I still believe we're loosing information here that an analyzer could leverage: if we passed in that the connection is partial, resync could start right away without waiting for an error to occur. That would be helpful if it's actually hard to understand if we're parsing things correctly, like with a binary protocol without a clear marker of a correct PDU. If we knew we are partial, we could then for example jump forward to, say, a particular message type.

That said, it's actually not so easy to provide that API for saying we're partial because it that information would need to be carried through with the stream. This sounds similar to how we want to eventually pass on gaps inside the input stream: by inserting a gap marker into the stream, which the parser can then pick up on. I think having that would also solve the issue here: we'd essentially insert a gap of unknown size right at the beginning. I'll close this ticket and leave a note in https://github.com/zeek/spicy/issues/1135, which tracks the gap reporting.
