### ISSUE TITLE
zeek/spicy: Built-in spicy modules cannot be replaced.

### ISSUE THREAD

**Issue by jlucovsky** [zeek/spicy-plugin#137]
When Zeek is built with built-in spicy modules and a custom spicy module is loaded that uses the `replaces` keyword for an existing spicy module, the existing spicy module is not replaced -- it's left loaded along with the custom spicy module which requested the replacement.

**Comment by rsmmr** [comment]
On closer inspection, I think the problem is a different one: that reproducer attempts to replace packet analyzer with a protocol analyzer. That can't work semantically, but the real problem is that packet analyzers currently do not support `replaces` anyways: only protocol and file analyzers do. The code says: ```

::spicy::zeek::compat::AnalyzerTag plugin::Zeek_Spicy::Plugin::tagForPacketAnalyzer(
    const ::spicy::zeek::compat::AnalyzerTag& tag) {
    // Don't have a replacement mechanism currently.
    return tag;
}

```

I changed the reproducer to use `replaces Telnet`, and that seems to work fine, the original Telnet analyzer ends up being disabled then:

```
[Analyzer] Telnet (ANALYZER_TELNET, disabled)
```

**Comment by rsmmr** [comment]
On the upside, Zeek just learned to disable packet analyzers, so I believe we should be able to implement this now. https://github.com/zeek/zeek/pull/2443

**Comment by rsmmr** [comment]
Ok, I can now also reproduce the original problem: the key is to have both (1) spicy-plugin built into Zeek, *and* (2) load the HLTO through `ZEEK_SPICY_MODULE_PATH` rather than the command-line. Will look into what's going on.
