### ISSUE TITLE
File Analysis Framework Filename Function

### ISSUE THREAD

**Issue by keithjjones** [zeek/spicy-plugin#200]
There is a filename listed in files.log (https://docs.zeek.org/en/master/scripts/base/frameworks/files/main.zeek.html#type-Files::Info) but there isn't a way to add a file name via Spicy with the functions available here: https://docs.zeek.org/projects/spicy/en/latest/zeek.html?highlight=file%20analysis%20framework#controlling-zeek-from-spicy

It would be nice to have a `set_file_name` function available in Spicy that will allow population of this field.  

Thanks!

**Comment by bbannier** [comment]
The issue in implementing this is that `fa_file$info$filename` is only available if Zeek's file analysis framework is loaded. This means that if we would implement this as described, we cannot use Zeek's File C++ API, but instead would need to dynamically add the information depending on what could be set. This is undesirable as it mixes C++ API.

There are multiple ideas on how one could provide this functionality instead. The simplest is probably to make `$file` also available for protocol analyzers so that it would refer to the most recent unclosed file. One could then use that in the EVT file
```
on foo::Bar::file_name -> event have_filename($file, self.file_name);
```
and consume that event in Zeek script
```
event have_filename(f: fa_file, filename: string)
	{
	# Implicitly assumes that `fa_file$info` is available, i.e., the file analysis framework is loaded.
	f$info$filename = filename;
	}
```
The slightly tricky bit about this is that as a user one needs to take care to have the interesting file on the top of the stack when setting the filename. The benefit of this API is that if `$file` can bind to a live value there is little danger of it becoming stale until the event is handled.

Does this sound like a workable solution @keithjjones?
