### ISSUE TITLE
Glue `replaces` statement should activate DPD rules of replaced analyzer for replacement

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy-plugin#69]
We can currently specify in the evt glue that an analyzer `replaces` an existing analyzer. In that case we deactivate the old analyzer before registering the replacement.

If the old analyzer had associated DPD rules they will still only `enable` the old analyzer and not the replacement. We should figure out a way to obtain rules matching a replacement, rewrite them to enable the new analyzer, and then add them the Zeek's `RuleMatcher`. This seems tricky as e.g., `RuleMatcher` does not seem to have an API to iterate or obtain previously added rules.

This is related to zeek/spicy-analyzers#88.

**Comment by rsmmr** [comment]
I'm gonna close this as I don't think we should re-use existing DPD rules for the new analyzers. Instead, a new analyzer should get to decide how it gets activated independent of what's already in place. Packet analyzers have similar property (since #141): one also needs to add new, dedicated activated rules for them, which seems right to me.
